################################################################################
############################ GOSSIP DATA ANALYSIS ##############################
################################################################################
#
# We study the mechanisms underlying gossiping using  data from the 'Wired into
# Each Other' longitudinal study conducted by the Research Center for Educational
# and Network Studies (RECENS) in Hungary.
#
# The dataset comes from a four-wave survey in 44 Hungarian secondary school 
# classes, across 7 schools in 4 Hungarian towns.
#



# -------------------------------------------------------------------------
# Load pre-processed gossip hyperevents dataset
# This dataset is generated by running pre_processing_data.R
# -------------------------------------------------------------------------
base_folder <- getwd()
load(file.path(base_folder, "gossipdata_analysis", "GossipData.RData"))


# -------------------------------------------------------------------------
# Load auxiliary R functions needed for analysis
# -------------------------------------------------------------------------
source(file.path(base_folder, "gossipdata_analysis", "functions_data.R"))
source(file.path(base_folder, "utils", "covariates.R"))




# -------------------------------------------------------------------------
# Define covariates for modeling
# -------------------------------------------------------------------------
# Exogenous covariates: independent variables that do not depend on past events
exogenous_covariates <- c("girl.ego", "girl.alter", "time_continuous")

# Endogenous covariates: network-based or history-dependent variables
endogenous_covariates <- c("sender.degree", "receiver.degree", "repetition", 
                           "subset.repetition", "reciprocity", "transitive.closure",
                           "cyclic.closure", "sender.balance", "receiver.balance")





################################################################################
# Construct the Risk Set 
################################################################################

# Identify maximum clique size among friends across all classes and waves
clique_info <- get_max_clique_size()

# Maximum number of possible senders in a gossip hyperevent (find in clique_info)
max_senders <- 6

# Global environment to track already-generated combinations (avoid duplicates)
existing_keys_global <- new.env(hash = TRUE, parent = emptyenv())

# Helper function: check if a student ID is valid according to its gender group
is_valid_id <- function(id) {
  if (is.na(id) || id == "") return(FALSE)
  id_chr <- as.character(id)
  gender_key <- paste0("gender_", substr(id_chr, 1, 2), "00")
  if (!gender_key %in% names(GossipData$info)) return(FALSE)
  return(as.numeric(id) %in% as.numeric(GossipData$info[[gender_key]]$idcode))
}




# List to store risk sets for all classes and waves
risk_set_list <- list()

# List of classes and waves to iterate over
info_names <- names(GossipData$info)
classes <- as.numeric(gsub("gender_", "", info_names))
n_years <- 4
waves <- paste0("Wave", 1:n_years)


for (class in classes) {
  
  # Map class ID to its corresponding folder name
  folder <- paste0(substr(as.character(class), 1, 1), "000")
  
  cat("\n--- Processing Class:", class, "---\n")
  
  gender_data_name <- paste0("gender_", class)
  idcode <- as.character(GossipData$info[[gender_data_name]]$idcode)
  
  for (Wave in waves) {
    cat("Processing", Wave, "\n")
    
    # Construct the file path for the friendship matrix
    friend_scale <- switch(Wave,
                           Wave1 = "15",
                           Wave2 = "11",
                           Wave3 = "19",
                           Wave4 = "20")
    friend_scale_all <- switch(Wave,
                               Wave1 = "15_1",
                               Wave2 = "11_2h",
                               Wave3 = "19_3h",
                               Wave4 = "20_4h")
    # Path
    base_folder <- getwd() 
    csv_file <- file.path(
      base_folder,
      "gossipdata_analysis",
      "gossipdata",
      "RECENS_Wired_into_each_other-Data_files",
      "RECENS_networks_dataset_w1234",
      Wave,        # e.g., "Wave1"
      folder,      # e.g., "1100"
      class,       # e.g., "1100"
      friend_scale, # e.g., "friend_scale1"
      paste0(class, "_", friend_scale_all, ".csv")
    )
    # Skip wave if file is missing
    if (!file.exists(csv_file)) {
      cat("CSV not found, skipping", Wave, "\n")
      next
    }
    friend <- read.csv(csv_file, row.names = 1)
    matrix_data <- as.matrix(friend)
    students <- rownames(matrix_data)
    
    # Skip if no valid student IDs are found for this class
    if (!any(substr(students, 1, 1) == substr(as.character(class), 1, 1))) {
      cat("No valid students found for this class, skipping", Wave, "\n")
      next
    }
    
    # Load gossip (negative gossip) data for the same class and wave
    if (Wave == "Wave1") {
      neg_gossip <- "33"
      neg_gossip_all <- "33_3"
    } else if (Wave == "Wave2") {
      neg_gossip <- "32"
      neg_gossip_all <- "32_3_2h"
    } else if (Wave == "Wave3") {
      neg_gossip <- "39"
      neg_gossip_all <- "39_3_3h"
    } else if (Wave == "Wave4") {
      neg_gossip <- "38"
      neg_gossip_all <- "38_3_4h"
    }
    # Path 
    base_folder <- getwd()  
    ngossip_path <- file.path(
      base_folder,
      "gossipdata_analysis",
      "gossipdata",
      "RECENS_Wired_into_each_other-Data_files",
      "RECENS_networks_dataset_w1234",
      Wave,
      folder,
      class,
      neg_gossip,
      paste0(class, "_", neg_gossip_all, ".csv")
    )
    NGossip <- read.csv(ngossip_path, row.names = 1)
    gossip_data <- as.matrix(NGossip)
    rows <- rownames(gossip_data)
    cols <- colnames(gossip_data)
    
    # All students mentioned in the gossip dataset
    all_students_class <- unique(c(rows, sub("^X", "", cols)))
    
    # Keep only valid individual IDs using the helper function
    valid_students <- all_students_class[sapply(all_students_class, is_valid_id)]
    
    # Extract reciprocated friendships
    indices <- which(matrix_data == 2, arr.ind = TRUE)
    pairs_of_friends <- t(apply(indices, 1, function(idx) {
      c(students[idx[1]], sub("^X", "", students[idx[2]]))
    }))
    pairs_sorted <- t(apply(pairs_of_friends, 1, sort))
    pairs_sorted <- pairs_sorted[pairs_sorted[,1] != pairs_sorted[,2], ]
    reciprocated_friends <- pairs_sorted[duplicated(pairs_sorted), ]
    
    # Skip this wave if no reciprocated friendships exist
    if (is.null(reciprocated_friends) || length(reciprocated_friends) == 0) {
      cat("No reciprocated friendships found, skipping this wave\n")
      next 
    }
    
    # Ensure data is always in matrix form
    if (is.vector(reciprocated_friends) && length(reciprocated_friends) == 2) {
      reciprocated_friends <- matrix(reciprocated_friends, ncol = 2, byrow = TRUE)
    } else if (!is.matrix(reciprocated_friends)) {
      reciprocated_friends <- as.matrix(reciprocated_friends)
    }
    
    # Filter friendship pairs to include only valid students
    filtered_friendships <- lapply(1:nrow(reciprocated_friends), function(i) as.character(reciprocated_friends[i,]))
    filtered_friendships <- Filter(function(pair) all(pair %in% students), filtered_friendships)
    if (length(filtered_friendships) == 0) next
    filtered_friendships_matrix <- do.call(rbind, filtered_friendships)
    
    # Generate the risk set for the current class and wave
    risk_df <- generate_risk_set(max_senders = max_senders, Wave = as.numeric(gsub("Wave","",Wave)))
    
    if (nrow(risk_df) > 0) {
      # Remove exact duplicates just in case
      risk_df <- risk_df %>%
        dplyr::mutate(SenderSet = sapply(Senders, function(x) paste(sort(x), collapse = ","))) %>%
        dplyr::distinct(SenderSet, Receiver, Time, .keep_all = TRUE) %>%
        dplyr::select(-SenderSet)
      
      # Append to the global risk set list
      risk_set_list <- append(risk_set_list, list(risk_df))
    }
  }
}
# Risk Set dataframe
Risk_set_df <- do.call(rbind, risk_set_list)
# Remove any residual duplicates
Risk_set_df <- Risk_set_df %>%
  dplyr::mutate(SenderSet = sapply(Senders, function(x) paste(sort(x), collapse = ","))) %>%
  dplyr::distinct(SenderSet, Receiver, Time, .keep_all = TRUE) %>%
  dplyr::select(-SenderSet)

cat("Total risk set rows with up to 6 senders:", nrow(Risk_set_df), "\n")





# Save the final risk set
base_folder <- getwd()  
save_folder <- file.path(base_folder, "gossipdata_analysis")
if (!dir.exists(save_folder)) {
  dir.create(save_folder, recursive = TRUE)
}
save(Risk_set_df, file = file.path(save_folder, "Riskset.RData"))

cat("\n Riskset.RData saved successfully in", save_folder, "!\n")








################################################################################
# Construct vector of observed hyperevents  
################################################################################

z_data <- define_vector_z(RiskSet = Risk_set_df, GossipData = GossipData)
# Print total number of observed events
print(sum(z_data))






################################################################################
# Compute exogenous covariates
################################################################################

# Store gender mapping
gender_map <- list()

for (class_info in GossipData$info) {
  # Extract idcode and gender
  ids <- class_info$idcode
  genders <- class_info$gender
  # Convert gender to 0 (male) and 1 (female)
  gender_binary <- ifelse(genders == 1, 0, 1)
  # Assign to gender_map using names
  for (i in seq_along(ids)) {
    gender_map[[as.character(ids[i])]] <- gender_binary[i]
  }
}


# Compute girl ego and girl alter as exogenous covariates 
girl.ego <- compute_covariates(RiskSet = Risk_set_df, gender_map = gender_map, CovariateName = "girl.ego")
girl.alter <- compute_covariates(RiskSet = Risk_set_df, gender_map = gender_map, CovariateName = "girl.alter")

Risk_set_df$girl.ego <- girl.ego
Risk_set_df$girl.alter <- girl.alter







################################################################################
# Compute endogenous covariate based on average evaluation 
################################################################################

# Initialize history and covariates
history_data <- list(time = numeric(0), receiver = character(0), sender = list())
cov_past    <- vector("list", length(endogenous_covariates))
cov_current <- vector("list", length(endogenous_covariates))
cov_avg     <- vector("list", length(endogenous_covariates))
names(cov_past)    <- endogenous_covariates
names(cov_current) <- endogenous_covariates
names(cov_avg)     <- endogenous_covariates


# Loop over events
for (i in 1:nrow(Risk_set_df)) {
  # Current event
  sender_i <- Risk_set_df$Senders[[i]]
  if (is.null(sender_i)) sender_i <- character(0)
  e <- list(
    time     = Risk_set_df$Time[i],
    receiver = Risk_set_df$Receiver[i],
    sender   = sender_i
  )
  
  # Past: history up to previous wave
  past_idx <- which(history_data$time < e$time)
  if(length(past_idx) == 0){
    history_past <- list(time = numeric(0), receiver = character(0), sender = list())
  } else {
    history_past <- list(
      time     = history_data$time[past_idx],
      receiver = history_data$receiver[past_idx],
      sender   = history_data$sender[past_idx]
    )
  }
  
  # Current: history up to current wave (included)
  if(length(history_data$time) == 0){
    history_current <- list(time = numeric(0), receiver = character(0), sender = list())
  } else {
    history_current <- history_data
  }
  e_current <- e
  e_current$time <- e_current$time + 1  # Include current wave
  
  # Compute covariate for Past, Current & Average
  for (cov in endogenous_covariates) {
    
    # Past
    if(length(history_past$time) == 0){
      cov_past[[cov]][i] <- 0
    } else {
      cov_past[[cov]][i] <- compute_covariates(CovariateName = cov, History = history_past, Event = e)
    }
    
    # Current
    if(length(history_current$time) == 0){
      cov_current[[cov]][i] <- 0
    } else {
      cov_current[[cov]][i] <- compute_covariates(CovariateName = cov, History = history_current, Event = e_current)
    }
    
    # Average
    cov_avg[[cov]][i] <- (cov_past[[cov]][i] + cov_current[[cov]][i]) / 2
  }
  
  # Update history only if z=1
  if (z_data[i] == 1) {
    history_data$time     <- c(history_data$time, e$time)
    history_data$receiver <- c(history_data$receiver, e$receiver)
    history_data$sender   <- append(history_data$sender, list(e$sender))
  }
}

# Build covariates from the AVERAGE history 
covariates_df <- as.data.frame(cov_avg)
colnames(covariates_df) <- paste0(gsub("\\.", "_", endogenous_covariates))  

# Main dataframe
data_df <- data.frame(
  z = z_data,  
  girl.alter = girl.alter, 
  girl.ego = girl.ego,
  time = Risk_set_df$Time
)

# Combine with average covariates
data_df<- cbind(data_df, covariates_df)








################################################################################
# Offset Term
################################################################################
# Waves have different lengths (in months): 2, 6, 12, 12
# Previously, we assumed equal spacing (log(1) = 0) 
# Now we add an offset term to to adjust for unequal wave durations

# Wave durations (months) 
durations <- c(2, 6, 12, 12)
# Assign each row the corresponding wave duration
data_df$duration_months <- durations[data_df$time]
# Log-duration offset term for modeling
data_df$offset_log <- log(data_df$duration_months)





# Continuous time variable (midpoint of each wave)
start_time <- cumsum(c(0, durations[-length(durations)]))  # wave start (0, 2, 8, 20)
mid_time <- start_time + durations / 2                     # midpoint (1, 5, 14, 26)
data_df$time_continuous <- mid_time[data_df$time]







################################################################################
# Include Random Effects
################################################################################

## Class Group
# Load student dataset containing class membership across waves
base_folder <- getwd()  
students_df <- read.csv(
  file.path(base_folder,
            "gossipdata_analysis",
            "gossipdata",
            "RECENS_Wired_into_each_other-Data_files",
            "RECENS_students_dataset_w1234.csv")
)
# Build a lookup table for each wave
students_lookup <- list(
  "1" = setNames(students_df$class_1, students_df$idcode),
  "2" = setNames(students_df$class_2, students_df$idcode),
  "3" = setNames(students_df$class_3, students_df$idcode),
  "4" = setNames(students_df$class_4, students_df$idcode)
)
# Function to return the class of a student given their ID and wave
get_class_for_student_fast <- function(student_id, time) {
  cls <- students_lookup[[as.character(time)]][as.character(student_id)]
  if (is.na(cls)) return(NA)
  return(cls)
}
# Function to return the most frequent (modal) class among senders + receiver
get_group_class_fast <- function(senders, receiver, time) {
  all_ids <- c(as.numeric(unlist(senders)), receiver)
  classes <- sapply(all_ids, get_class_for_student_fast, time = time)
  classes <- na.omit(classes)
  if (length(classes) == 0) return(NA)
  class_mode <- as.numeric(names(sort(table(classes), decreasing = TRUE)[1]))
  return(class_mode)
}
library(pbapply)
data_df$ClassGroup <- pbmapply(
  get_group_class_fast,
  Risk_set_df$Senders,
  Risk_set_df$Receiver,
  Risk_set_df$Time
)
data_df$ClassGroup <- factor(data_df$ClassGroup)
# Check the resulting class distribution
table(data_df$ClassGroup, useNA = "ifany")



## Receiver Group
data_df$ReceiverGroup <- factor(Risk_set_df$Receiver)



## Sender Group
data_df$SenderGroup <- factor(sapply(Risk_set_df$Senders, function(s) {
  paste(sort(as.character(s)), collapse = "_")
}))







################################################################################
# Fit a Generalized Additive Model (GAM) using bam() from mgcv
################################################################################

library(mgcv)

# Formula
formula <- z ~ girl.alter + 
  s(girl.ego) + 
  s(time_continuous, k=4) +    
  s(log(sender_degree +1)) +
  s(log(receiver_degree +1), k=8) + 
  s(repetition, k=4) +
  s(subset_repetition) +
  s(reciprocity) + 
  s(transitive_closure, k=6) + 
  s(cyclic_closure) + 
  s(sender_balance) + 
  s(receiver_balance, k=8) + 
  s(ClassGroup, bs="re") +
  s(ReceiverGroup, bs="re") +
  s(SenderGroup, bs="re") +
  offset(offset_log)             # offset term



model_with_re <- bam(
  formula,
  data = data_df,
  family = binomial(link = "cloglog"),
  method = "fREML",
  select = TRUE,      # penalize irrelevant smooth terms
  discrete = TRUE     # faster for large datasets
)

# Summary
model_summary_with_re <- summary(model_with_re)
cat("\n==================== Model ====================\n")
print(model_summary_with_re)




################################################################################
# Unobserved heterogeneity for random effects (class, receiver, sender set)
################################################################################
gam.vcomp(model_with_re)




################################################################################
# Plot Smooth Effects with mgcViz
################################################################################
library(ggplot2)
library(mgcViz)

p <- getViz(model_with_re)


# Proportion of girls in the sender set
plot(sm(p, 1)) +
  l_fitLine() +
  l_ciLine() +
  l_rug() +
  theme_classic() +
  labs(x = "girl ego", y = "log-hazard contribution") +
  theme(
    axis.title.x = element_text(size = 18, margin = margin(t = 15)),   # X-axis label size
    axis.title.y = element_text(size = 18, margin = margin(r = 15)),   # Y-axis label size
    axis.text.x = element_text(size = 18),    # X-axis tick labels
    axis.text.y = element_text(size = 18),    # Y-axis tick labels
  )


# Sender activity
plot(sm(p, 3)) +
  l_fitLine() +
  l_ciLine() +
  l_rug() +
  theme_classic() +
  labs(x = "sender degree", y = "log-hazard contribution") +
  theme(
    axis.title.x = element_text(size = 18, margin = margin(t = 15)),    # X-axis label size
    axis.title.y = element_text(size = 18, margin = margin(r = 15)),   # Y-axis label size
    axis.text.x = element_text(size = 18),    # X-axis tick labels
    axis.text.y = element_text(size = 18),    # Y-axis tick labels
  )


# Receiver activity
plot(sm(p, 4)) +
  l_fitLine() +
  l_ciLine() +
  l_rug() +
  theme_classic() +
  labs(x = "receiver degree", y = "log-hazard contribution") +
  theme(
    axis.title.x = element_text(size = 18, margin = margin(t = 15)),   # X-axis label size
    axis.title.y = element_text(size = 18, margin = margin(r = 15)),   # Y-axis label size
    axis.text.x = element_text(size = 18),    # X-axis tick labels
    axis.text.y = element_text(size = 18),    # Y-axis tick labels
  )



# Repetition of gossiping from subsets of the sender set
plot(sm(p, 6)) +
  l_fitLine() +
  l_ciLine() +
  l_rug() +
  theme_classic() +
  labs(x = "subset repetition", y = "log-hazard contribution") +
  theme(
    axis.title.x = element_text(size = 18, margin = margin(t = 15)),   # X-axis label size
    axis.title.y = element_text(size = 18, margin = margin(r = 15)),   # Y-axis label size
    axis.text.x = element_text(size = 18),    # X-axis tick labels
    axis.text.y = element_text(size = 18),    # Y-axis tick labels
  )










################################################################################
# A more complex model including interaction effects
################################################################################

# Evaluating potential gender interaction effects in the dynamics of gossiping

library(mgcv)
data_df$log_sender_degree <- log(data_df$sender_degree + 1)
data_df$log_receiver_degree <- log(data_df$receiver_degree + 1)



formula_te_re <- z ~ girl.alter +
  
  s(time_continuous, k = 4) +
  
  te(log_receiver_degree, girl.ego, by = factor(girl.alter)) +
  te(log_sender_degree, girl.ego, by = factor(girl.alter)) +
  te(subset_repetition, girl.ego, by = factor(girl.alter)) +
  
  s(ClassGroup, bs = "re") +
  s(ReceiverGroup, bs = "re") +
  s(SenderGroup, bs = "re") +
  
  offset(offset_log)


model_te_re <- bam(
  formula_te_re,
  data = data_df,
  family = binomial(link = "cloglog"),
  method = "fREML",
  select = TRUE,
  discrete = TRUE
)

summary(model_te_re)
BIC(model_te_re)

################################################################################
# MODEL DIAGNOSTICS
################################################################################

plot(model_te_re, pages = 1, scale = 0)
gam.vcomp(model_te_re)



################################################################################
# 3D SURFACE PLOTS (vis.gam)
################################################################################

par(mfrow = c(2, 3))

# SENDER DEGREE x GIRL EGO x GIRL ALTER = MALE 
par(mar = c(5, 6, 4, 2), cex.lab = 1.5, cex.axis = 1.5, lwd = 2, font.lab = 1)
vis.gam(model_te_re,
        view = c("log_sender_degree", "girl.ego"),
        cond = list(girl.alter = 0),
        target = "link",
        theta = 30, phi = 30,
        xlab = "sender degree",    
        ylab = "girl ego",      
        color = "terrain",      
        plot.type = "contour",
        contour.col = "black",
        main = "male receiver",  
        ticktype = "detailed",
        cex.main = 2,
        labcex = 1.5,
        lwd = 2,
        nlevels = 12) 

# SENDER DEGREE x GIRL EGO x GIRL ALTER = FEMALE 
par(mar = c(5, 6, 4, 2), cex.lab = 1.5, cex.axis = 1.5, lwd = 2, font.lab = 1)
vis.gam(model_te_re,
        view = c("log_sender_degree", "girl.ego"),
        cond = list(girl.alter = 1),
        type = "link",
        theta = 30, phi = 30,
        xlab = "sender degree",    
        ylab = "girl ego",     
        color = "terrain",
        plot.type = "contour",
        contour.col = "black",
        main = "female receiver",   
        ticktype = "detailed",
        cex.main = 2,
        labcex = 1.5,
        lwd = 2,
        nlevels = 12)

# RECEIVER DEGREE x GIRL EGO x GIRL ALTER = MALE
par(mar = c(5, 6, 4, 2), cex.lab = 1.5, cex.axis = 1.5, lwd = 2, font.lab = 1)
vis.gam(model_te_re,
        view = c("log_receiver_degree", "girl.ego"),
        cond = list(girl.alter = 0),
        target = "link",
        theta = 30, phi = 30,
        xlab = "receiver degree",    
        ylab = "girl ego",      
        color = "terrain",     
        plot.type = "contour",
        contour.col = "black",
        main = "male receiver",  
        ticktype = "detailed",
        cex.main = 2,
        labcex = 1.5,
        lwd = 2,
        nlevels = 12)

# RECEIVER DEGREE x GIRL EGO x GIRL ALTER = FEMALE 
par(mar = c(5, 6, 4, 2), cex.lab = 1.5, cex.axis = 1.5, lwd = 2, font.lab = 1)
vis.gam(model_te_re,
        view = c("log_receiver_degree", "girl.ego"),
        cond = list(girl.alter = 1),
        type = "link",
        theta = 30, phi = 30,
        xlab = "receiver degree",    
        ylab = "girl ego",     
        color = "terrain",
        plot.type = "contour",
        contour.col = "black",
        main = "female receiver",  
        ticktype = "detailed",
        cex.main = 2,
        labcex = 1.5,
        lwd = 2,
        nlevels = 12)

# SUBSET REPETITION x GIRL EGO x GIRL ALTER = MALE 
par(mar = c(5, 6, 4, 2), cex.lab = 1.5, cex.axis = 1.5, lwd = 2, font.lab = 1)
vis.gam(model_te_re,
        view = c("subset_repetition", "girl.ego"),
        cond = list(girl.alter = 0),
        target = "link",
        theta = 30, phi = 30,
        xlab = "subset repetition",    
        ylab = "girl ego",      
        color = "terrain",      
        plot.type = "contour",
        contour.col = "black",
        main = "male receiver",  
        ticktype = "detailed",
        cex.main = 2,
        labcex = 1.5,
        lwd = 2,
        nlevels = 12)

# SUBSET REPETITION x GIRL EGO x GIRL ALTER = FEMALE
par(mar = c(5, 6, 4, 2), cex.lab = 1.5, cex.axis = 1.5, lwd = 2, font.lab = 1)
vis.gam(model_te_re,
        view = c("subset_repetition", "girl.ego"),
        cond = list(girl.alter = 1),
        type = "link",
        theta = 30, phi = 30,
        xlab = "subset repetition",    
        ylab = "girl ego",     
        color = "terrain",
        plot.type = "contour",
        contour.col = "black",
        main = "female receiver",   
        ticktype = "detailed",
        cex.main = 2,
        labcex = 1.5,
        lwd = 2,
        nlevels = 12)








################################################################################
# PREDICTIONS ON FULL RISK SET
################################################################################

cat("\n--- Predictions ---\n")

eta_hat <- predict(model_te_re, newdata = data_df, type = "link")
mu_hat  <- predict(model_te_re, newdata = data_df, type = "response")
risk_hat <- exp(eta_hat)

data_df$mu_hat <- mu_hat
data_df$eta_hat <- eta_hat
data_df$risk_hat <- risk_hat

################################################################################
# SAVE RESULTS
################################################################################

save(model_te_re,
     file = "model_te_re_revision_final.RData")

save(data_df,
     file = "prediction_riskset_revision_final.RData")

################################################################################
# HISTOGRAM OF RANKS
################################################################################

r1 <- rank(mu_hat)[data_df$z == 1] # events
r0 <- rank(mu_hat)[data_df$z == 0] # non-events

# 1st hist (events) 
hist(r1, xlim = c(1, 300000), ylim = c(0,0.00015), prob = TRUE, 
     col = rgb(0.2, 0.2, 0.2, 0.6), border = "black",
     xlab = "rank of predicted intensity",
     ylab = "density",
     cex.lab = 1.5, 
     cex.axis = 1.3,   
     main = "")

# 2nd hist (non-events)
hist(r0, add = TRUE, prob = TRUE, 
     col = rgb(0.8, 0.8, 0.8, 0.6), border = "black")

legend(x = 8000, y = 0.00015, , legend = c("events", "non-events"),
       fill = c(rgb(0.2,0.2,0.2,0.6), rgb(0.8,0.8,0.8,0.6)), border = "black",
       bty = "n",
       cex = 1.5) 

dev.off()
